source "https://rubygems.org"

gem "jekyll", "~> 4.4.1"
gem "minima", "~> 2.5"
gem "logger"
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows-specific gems (simplified)
platforms :mingw do
  gem "tzinfo"
  gem "tzinfo-data"
end